[package]
name = "crate_name"
version = "0.1.0"
authors = ["Author Name <author@example.com>"]

# the profile used for `cargo build`
[profile.dev]

# the profile used for `cargo build --release`
[profile.release]

[[bin]]
name = "blog_os"
test = false
bench = false